// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUnUj2X38xYOhzwB3pQEDXjfHw4lAC3lU',
    appId: '1:254546470262:web:58b11df8cc65520ad58657',
    messagingSenderId: '254546470262',
    projectId: 'student-card-appointment-f7812',
    authDomain: 'student-card-appointment-f7812.firebaseapp.com',
    storageBucket: 'student-card-appointment-f7812.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Uu3nR_T9hLMNJ-kQXWZwuxCC9wEZvTw',
    appId: '1:254546470262:android:078b97a344807b25d58657',
    messagingSenderId: '254546470262',
    projectId: 'student-card-appointment-f7812',
    storageBucket: 'student-card-appointment-f7812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgtbGz3Kq7FGRNqMKYLIaank7L-M4T5s',
    appId: '1:254546470262:ios:86ac8260c982736ad58657',
    messagingSenderId: '254546470262',
    projectId: 'student-card-appointment-f7812',
    storageBucket: 'student-card-appointment-f7812.appspot.com',
    iosBundleId: 'com.example.studentMysiswa',
  );
}
